### PR TITLE
vscode: theme parts of the editor more

### PR DESCRIPTION
**Pull request by nopjmp**
This needs some looking over on colors and making sure colors mesh well.

Copied over from my fairyfloss vscode port and added a few more things I never got around.

I wasn't sure on what on what would be acceptable for accent colors around the editor so I took some queues that I did and add them around. Green for the badges looked okay as well and I wasn't sure if that was what everyone would want for this theme, so I went with the pink variant.

### CODE REVIEW

**Comment by theacodes** [comment]
Awesome! Thank you for doing this. I'm traveling so I can't try this out
right now, but if you wanna post a picture I'll be happy to merge it sooner!

**Comment by nopjmp** [comment]
image
#C2FFDF is what I was going to use for the badges which would make the badge and base the buttons off green. But I went with the pink since I already had that mostly done.

Would green be better?
image

image

**Comment by theacodes** [comment]
Oh this looks wonderful. We can merge with pink for now and if you wanna
change it to use green or maybe the lighter blue later we can do that.

**Comment by nopjmp** [comment]
okay sounds good, I'll play around with the lighter blue to see how it looks. You can merge if you want.

**Comment by nopjmp** [comment]
image
Blue badge

**Comment by theacodes** [comment]
Awesome. Thank you for doing this!

**Comment by nopjmp** [comment]
you may want to bump the vscode version and publish again so users can get the latest changes too :)

I'll probably be using it, so I'll submit patches as I find bugs!

**Comment by theacodes** [comment]
I did! It's released. Thank you so much.

**Pull request merged**
