### PR TITLE
pywal / pywal16 and mintty versions

### PR DESCRIPTION
**Pull request by clach04**
Based on alacritty / kitty.

# What is this PR about?

Implements themes for pywal, for generating themes for all sorts of tools. As well as mintty the Terminal Emulator.

(Describe what are the changes and why you have made them.)

# Which editor(s) does this change concern?

- [ ] VS Code
- [ ] Sublime
- [ ] JetBrains
- [ ] Atom
- [ ] Pygments
- [x] Other: Not an editor, this is for terminal mintty and pywal the theme generator
- [ ] 
# The changes are for following theme variant(s):

- [x] Hypercolor
- [x] Classic

# Screenshots

witchhazel

witchhazel_hyper

### CODE REVIEW

**Comment by clach04** [comment]
NOTE the screen shot previews in GitHub are NOT accurate. Clicking on them shows the real colors. I'm trying to figure this out...

**Comment by theacodes** [comment]
> NOTE the screen shot previews in GitHub are NOT accurate. Clicking on them shows the real colors. I'm trying to figure this out...

Maybe some weirdness with ICC profiles? Either way, they look good to me! I'll go ahead and merge this.

**Comment by clach04** [comment]
Experiment with alternative links to screenshots:

https://private-user-images.githubusercontent.com/424032/399198925-4035c3c5-6927-492e-9f8a-de872f11013a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjMzNzQsIm5iZiI6MTczNTUyMzA3NCwicGF0aCI6Ii80MjQwMzIvMzk5MTk4OTI1LTQwMzVjM2M1LTY5MjctNDkyZS05ZjhhLWRlODcyZjExMDEzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQwMTQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDY4MDFkYTA3MzAzZmM2MWI3YWQ2NDU5YTNjZDllMjM1OGJkNTAyMWFhNjQyMzg0MmU0YzE1MTM5ZmY5YWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jnQkE8pb4pubxe_EBiEPUySL49Ldrs58YszahY5cY4A

https://private-user-images.githubusercontent.com/424032/399198933-1cb77bef-2e1a-4b1b-a94e-4db1ba501a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjMzNzQsIm5iZiI6MTczNTUyMzA3NCwicGF0aCI6Ii80MjQwMzIvMzk5MTk4OTMzLTFjYjc3YmVmLTJlMWEtNGIxYi1hOTRlLTRkYjFiYTUwMWEzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQwMTQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGI3MjcxMTE1Nzc2ZmMxYmRhZWViZGRiM2MzZTI0NjRhMzNmM2JlNmFmOTNlNTA0ODcyMTJhZmIzNjAyMjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TSZN9z5ABGa8OMsPcv5RGYtWGuaChql1gspzAT2OyVE

copy and paste of the url shown when clicking on images in description.

**Comment by clach04** [comment]
> > NOTE the screen shot previews in GitHub are NOT accurate. Clicking on them shows the real colors. I'm trying to figure this out...
> 
> Maybe some weirdness with ICC profiles? Either way, they look good to me! I'll go ahead and merge this.

that was fast! Thanks for making your theme available and accepting these!

Screen shots are from mintty under Windows 10.

**Comment by theacodes** [comment]
You lucked out and caught me during my sunday-night PR review marathon. :)

**Pull request merged**
